### ISSUE TITLE
pluginval will run forever when timeout_ms is set to -1

### ISSUE THREAD

**Issue by zsliu98** [Tracktion/pluginval#114]
See [this action](https://github.com/ZL-Audio/ZLTest/actions/runs/6038083212/job/16383670972) where I set timeout as an environment variable:
```yml
    - name: Pluginval VST3 validations
      working-directory: ${{ env.BUILD_DIR }}
      shell: bash
      run: |
        ${{ matrix.pluginval-binary }} --verbose --validate "${{ env.VST3_PATH }}"
      env:
        STRICTNESS_LEVEL: 10
        TIMEOUT_MS: -1
        REPEAT: 4
```
and [this action](https://github.com/ZL-Audio/ZLTest/actions/runs/6038217096/job/16384115802) where I specify it in the command:
```yml
    - name: Pluginval VST3 validations
      working-directory: ${{ env.BUILD_DIR }}
      shell: bash
      run: |
        ${{ matrix.pluginval-binary }} --verbose --timeout-ms -1 --validate "${{ env.VST3_PATH }}"
      env:
        STRICTNESS_LEVEL: 10
        REPEAT: 4
```
In both cases, pluginval will output some welcome messages and run forever (> 5 mins without output).
I am not sure whether it is the correct way to specify the timeout. Any ideas?
