### ISSUE TITLE
Using --validate-in-process from command line never exits

### ISSUE THREAD

**Issue by jmbockhorst** [Tracktion/pluginval#26]
When validating plugins from the command line on Windows, I have ran into a situation where the pluginval.exe process never quits (even after the tests pass), causing my bash script to never exit, which causing my CI to run forever. Removing the `--validate-in-process` fixes this, but I think supposed to be used for CI validation to work correctly (Correct me if I'm wrong).

**Comment by drowaudio** [comment]
Are you sure? We run that with all our plugins on our CI and it exits cleanly.
Is this on a build machine or local machine?

**Comment by jmbockhorst** [comment]
It happens on both an Azure Pipelines Windows build machine from bash script and on my local windows machine.

**Comment by 2-shell** [comment]
+1 We run into similar issues:

Running pluginval via Gtlab-CI on a Windows 10 physical, local machine (not used for anything else).

Relevant parts of the CI job configuration:
```yaml
pluginval_win:
  stage: test
  variables:
    GIT_STRATEGY: none
    CONFIGURATION: Release
    STRICTNESS_LEVEL: "5"
    RANDOM_SEED: "0x236c570"
    VERBOSE: "0"
    VALIDATE_IN_PROCESS: "1"
    SKIP_GUI_TESTS: "1"
  interruptible: true
  timeout: 10 minutes
  script:
    # Set UTF8 code page to avoid issues with displaying build output in gitlab
    - CHCP 65001
    - "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Windows.zip -OutFile pluginval.zip"
    - Expand-Archive pluginval.zip -DestinationPath .
    - $result=Start-Process -PassThru -Wait -FilePath "./pluginval.exe" -ArgumentList "--output-dir", "./artifacts", "--validate", "./MyPlugin.dll"
    - rm pluginval.*
    - 'if (!($result.ExitCode -eq 0)) { exit 1 }'
```

Please forgive me any crude things about this PS script - I'm a bash guy ;-)

However, initially I had simply run pluginval [as suggested in the documentation](https://github.com/Tracktion/pluginval/blob/develop/docs/Adding%20pluginval%20to%20CI.md#windows), but that didn't work for me, since gitlab-runner uses Powershell by default and that actually suits me, so I didn't want to change that. 

Simply running pluginval.exe didn't work, since it returns immediately and runs asynchronously. This is the reason why I google-implemented the `Start-Process` approach. 

Now, when I run the tests manually - they pass.  
Also, *sometimes* the CI job will pass as well.  
But more often than not, it runs until the CI script timeout (which I reduced to 10 minutes to avoid blocking my CI nodes) is reached.

I'm almost certain, that it is related to the way I'm running it, but I can't spot, what I'm missing.   
@jmbockhorst are your issues similar? Are you using powershell or cmd.exe to run pluginval?

Any help would be very welcome ;-)
